name: "Deploy To Heroku T3-App"

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7 # This is the action we are importing
        with: # It accepts some arguments to work, we can pass the argument using `with`
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}} # This is the same as the auth key we generated earlier
          heroku_app_name: "t3-iic3103-jacouyoumdjian" #Must be unique in Heroku
          heroku_email: "jacouyoumdjian@uc.cl" # Email attached to the account
      - name: Run a one-line script
        run: echo successfully run
